In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
! pip install pydub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pydub
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub
Successfully installed pydub-0.25.1

In [ ]:
from os import path
from pydub import AudioSegment

# files
mp3_file = "/content/drive/MyDrive/Colab Notebooks/labeled data/AU00720.mp3"
wav_filename = "AU00720.wav"

# convert wav to mp3
sound = AudioSegment.from_mp3(mp3_file)
sound.export(wav_filename, format="wav")

In [ ]:
from os import path
from pydub import AudioSegment
m4a_file = '/content/drive/MyDrive/Colab Notebooks/labeled data/AU03818_2.m4a'
wav_filename = r"AU03818_2.wav"
from pydub import AudioSegment
track = AudioSegment.from_file(m4a_file,  format= 'm4a')
file_handle = track.export(wav_filename, format='wav')

In [ ]:
!pip install vosk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vosk
  Downloading vosk-0.3.42-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 13.9 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from vosk) (2.23.0)
Collecting srt
  Downloading srt-3.5.2.tar.gz (24 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from vosk) (4.64.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.7/dist-packages (from vosk) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0->vosk) (2.21)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->vosk) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->vosk) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->vosk) (2022.5.18.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->vosk) (1.24.3)
Building wheels for collected packages: srt
  Building wheel for srt (setup.py) ... done
  Created wheel for srt: filename=srt-3.5.2-py3-none-any.whl size=22487 sha256=13f69c541bc481402d0a8211e1633ff63124a353bd193ba2693af84ffd9e4519
  Stored in directory: /root/.cache/pip/wheels/54/c4/ec/4604122e072aebb16803c8297b7cd3f4c72073a3ee58738015
Successfully built srt
Installing collected packages: srt, vosk
Successfully installed srt-3.5.2 vosk-0.3.42

In [ ]:
class Word:
    ''' A class representing a word from the JSON format for vosk speech recognition API '''

    def __init__(self, dict):
        '''
        Parameters:
          dict (dict) dictionary from JSON, containing:
            conf (float): degree of confidence, from 0 to 1
            end (float): end time of the pronouncing the word, in seconds
            start (float): start time of the pronouncing the word, in seconds
            word (str): recognized word
        '''

        self.conf = dict["conf"]
        self.end = dict["end"]
        self.start = dict["start"]
        self.word = dict["word"]

    def to_string(self):
        ''' Returns a string describing this instance '''
        return "{:20} from {:.2f} sec to {:.2f} sec, confidence is {:.2f}%".format(
            self.word, self.start, self.end, self.conf*100)

In [ ]:
import os
import sys
import wave
import json

from vosk import Model, KaldiRecognizer, SetLogLevel

SetLogLevel(0)
model_path = "/content/drive/MyDrive/Colab Notebooks/ML /Speaking IELTS project/models/vosk-model-en-us-0.22"
model = Model(model_path)

In [ ]:
#reading file
audio_filename="AU03818_2.wav"
wf = wave.open(audio_filename, "rb")

#recognize
rec = KaldiRecognizer(model, wf.getframerate())
rec.SetWords(True)
results = []

# recognize speech using vosk model
while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        part_result = json.loads(rec.Result())
        results.append(part_result)

part_result = json.loads(rec.FinalResult())
results.append(part_result)

In [ ]:
import pandas as pd
data = pd.DataFrame(results)
data=pd.concat([data.drop(['result'], axis=1), data['result'].apply(pd.Series)], axis=1)
data=data.drop(['text'], axis=1)
data=data.stack().reset_index()
data=data.drop(['level_0','level_1'], axis=1)
data=pd.concat([data.drop([0], axis=1), data[0].apply(pd.Series)], axis=1)
data=data.sort_values('start')
data['hesitation']=data['start']-data['end'].shift(1)
data

         conf     end       start   word  hesitation
0    1.000000    1.14    0.570000   part         NaN
1    1.000000    1.80    1.260000    two    0.120000
2    1.000000    2.70    2.550000      i    0.750000
3    0.784957    2.91    2.700000  don't    0.000000
4    1.000000    3.24    2.970000   have    0.060000
..        ...     ...         ...    ...         ...
280  1.000000  114.78  114.540000    for    0.030000
281  1.000000  115.20  114.780000   this    0.000000
282  0.794967  115.83  115.680000    all    0.480000
283  0.984314  116.01  115.835771     my    0.005771
284  0.762834  116.40  116.010000    own    0.000000

[285 rows x 5 columns]

In [ ]:
data.to_csv('AU03818_2.csv')
data.describe()

             conf         end       start  hesitation
count  285.000000  285.000000  285.000000  284.000000
mean     0.961514   56.049408   55.714427    0.071692
std      0.099358   33.349013   33.332495    0.180751
min      0.500628    1.140000    0.570000    0.000000
25%      1.000000   26.550000   26.220000    0.000000
50%      1.000000   54.720000   54.300000    0.000000
75%      1.000000   84.570000   84.300000    0.030000
max      1.000000  116.400000  116.010000    1.620000

In [ ]:
import zlib
print(zlib.crc32(b'PHAM NGUYEN XUAN NHIEN'))

3612871448

In [ ]:
data=pd.read_csv('AU03618.csv')
data.describe()

       Unnamed: 0        conf         end       start  hesitation
count  223.000000  223.000000  223.000000  223.000000  222.000000
mean   111.000000    0.960757   48.718565   48.377071    0.079671
std     64.518731    0.098976   28.006456   28.001682    0.200051
min      0.000000    0.434951    2.280000    1.770000    0.000000
25%     55.500000    1.000000   24.525000   24.135000    0.000000
50%    111.000000    1.000000   47.430000   47.340000    0.000000
75%    166.500000    1.000000   73.845000   73.560000    0.060000
max    222.000000    1.000000   95.610000   94.980000    1.260000